apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: lamport-clocks
  name: lamport-clocks
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lamport-clocks
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: lamport-clocks
        actorSystemName: lamport-clocks
    spec:
      containers:
        - name: lamport-clocks
          image: lamport-clocks:1.0
          imagePullPolicy: Never
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /ready
              port: management
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /alive
              port: management
          ports:
            # akka remoting
            - name: remoting
              containerPort: 2552
              protocol: TCP
            # akka-management bootstrap
            - name: management
              containerPort: 8558
              protocol: TCP
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: K8S_NAMESPACE
              value: "default"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lamport-clocks
  name: lamport-clocks
spec:
  type: NodePort
  selector:
    app: lamport-clocks
  ports:
    - name: remoting
      protocol: TCP
      port: 2552
    - name: management
      protocol: TCP
      port: 8558
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
  namespace: default
subjects:
  # Note the `name` line below. The first default refers to the namespace. The second refers to the service account name.
  # For instance, `name: system:serviceaccount:myns:default` would refer to the default service account in namespace `myns`
  - kind: User
    name: system:serviceaccount:default:default
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
